import { StyleSheet } from 'react-native';
import { colors } from '../../utils/constants/colors';
import { Fonts } from '../../utils/constants/UIConsts';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    height: '100%',
  },
  header: {
    width: '100%',
    borderBottomWidth: 1,
    borderColor: colors.primary,
    paddingBottom: 10,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
    marginTop: 11,
    // backgroundColor: 'red',
  },
  img: {
    width: 200,
    height: 200,
    resizeMode: 'contain',
    marginTop: 50,
  },
  title: {
    textAlign: 'center',
    marginTop: 10,
    fontFamily: Fonts.CairoBold,
    fontSize: 25,
  },
  chatCont: {
    flexGrow: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    justifyContent: 'flex-end',
    gap: 5,
    paddingBottom: 100,
  },
  welcomeCont: {
    alignItems: 'center',
  },
  welcomeText: {
    color: colors.primary,
    textAlign: 'center',
    fontFamily: Fonts.CairoBold,
    fontSize: 25,
  },
  welcomDesc: {
    textAlign: 'center',
    fontFamily: Fonts.Cairo,
    fontSize: 20,
    color: colors.subtitle,
  },
  userMsgCont: {
    alignItems: 'flex-start',
    marginTop: 10,
    alignSelf: 'flex-start',
    maxWidth: '70%',
    backgroundColor: colors.card,
    borderRadius: 20,
    paddingHorizontal: 10,
  },
  userMsgText: {
    color: colors.darkText,
    fontFamily: Fonts.Cairo,
    fontSize: 15,
  },
  aiMsgCont: {
    alignItems: 'flex-end',
    marginTop: 10,
    alignSelf: 'flex-end',
    maxWidth: '70%',
    backgroundColor: colors.primary,
    borderRadius: 20,
    padding: 10,
  },
  aiMsgText: {
    color: '#fff',
    fontFamily: Fonts.Cairo,
    fontSize: 15,
  },
  inputCont: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    alignSelf: 'center',
    width: '100%',
    position: 'absolute',
    bottom: 0,
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 20,
    borderTopWidth: 1,
    borderColor: colors.primary,
    backgroundColor: '#fff',
  },
  inputBox: {
    height: 60,
    flex: 5,
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 12,
    fontFamily: Fonts.Cairo,
    fontSize: 15,
    color: colors.darkText,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
    textAlignVertical: 'center',
    paddingVertical: 15,
    // verticalAlign: 'middle',
  },
  sendBtn: {
    backgroundColor: colors.primary,
    flex: 1,
    alignItems: 'center',
    height: '100%',
    justifyContent: 'center',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  sendText: {
    color: colors.bg,
    fontFamily: Fonts.CairoBold,
    fontSize: 15,
  },
  focusedText: {
    color: colors.primary,
    fontFamily: Fonts.CairoBold,
  },
  loaderCont: {
    width: 82,
    height: 80,
    borderRadius: 10,
    justifyContent: 'center',
    alignSelf: 'flex-end',
  },
});
